name: Memories App Server Deploy
on:
  push:
    branches: ['main']

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/Checkout@v2

      - name: SSH to server for deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |-
            sudo apt-get update
            sudo apt-get install git -y
            echo "--NODE & NPM--"
            sudo apt install nodejs -y
            sudo apt install npm -y
            echo "-----PM2------"
            sudo npm install -g pm2
            sudo pm2 startup systemd
            echo "-----NGINX------"
            sudo apt-get install -y nginx
            echo "---FIREWALL---"
            sudo ufw allow OpenSSH
            sudo ufw allow 'Nginx Full'
            sudo ufw --force enable 
            cd /home/ubuntu
            sudo rm -rf memories-server
            git clone https://github.com/eniolastyle/memories-server.git
            cd memories-server
            npm install
            sudo rm /etc/nginx/sites-available/default
            sudo cp default /etc/nginx/sites-available/ -r
            sudo pm2 kill
            pm2 start index.js
            sudo systemctl kill nginx || true
            sudo systemctl restart nginx
            
